// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:flutter/widgets.dart';
import 'package:routefly/routefly.dart';

import 'app/admin/chat/admin_chat_page.dart' as a0;
import 'app/admin/overview/overview_page.dart' as a1;
import 'app/admin/rooms/room_form_page.dart' as a3;
import 'app/admin/rooms/rooms_page.dart' as a2;
import 'app/admin/staff/staff_form_page.dart' as a4;
import 'app/admin/staff/staff_page.dart' as a5;
import 'app/login/login_page.dart' as a6;
import 'app/shared/chat/ai_chat_page.dart' as a7;
import 'app/shared/chat/chat_page.dart' as a8;
import 'app/shared/notes/notes_page.dart' as a9;
import 'app/splash/splash_page.dart' as a10;
import 'app/staff/home/room_detail_page.dart' as a11;
import 'app/staff/home/staff_dashboard_page.dart' as a12;
import 'app/staff/home/staff_rooms_page.dart' as a13;
import 'app/staff/settings/change_password_page.dart' as a14;

Route b0Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a0.AdminChatPage());
Route b1Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a1.OverviewPage());
Route b2Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a2.RoomsPage());
Route b3Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a3.RoomFormPage());
Route b4Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a4.StaffFormPage());
Route b5Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a5.StaffPage());
Route b6Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a6.LoginPage());
Route b7Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a7.AiChatPage());
Route b8Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a8.ChatPage());
Route b9Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a9.NotesPage());
Route b10Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a10.SplashPage());
Route b11Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a11.RoomDetailPage());
Route b12Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a12.StaffDashboardPage());
Route b13Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a13.StaffRoomsPage());
Route b14Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a14.ChangePasswordPage());
