// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
  RouteEntity(
    key: '/admin/chat/admin_chat',
    uri: Uri.parse('/admin/chat/admin_chat'),
    routeBuilder: b0Builder,
  ),
  RouteEntity(
    key: '/admin/overview',
    uri: Uri.parse('/admin/overview'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(
    key: '/admin/rooms',
    uri: Uri.parse('/admin/rooms'),
    routeBuilder: b2Builder,
  ),
  RouteEntity(
    key: '/admin/rooms/room_form',
    uri: Uri.parse('/admin/rooms/room_form'),
    routeBuilder: b3Builder,
  ),
  RouteEntity(
    key: '/admin/staff/staff_form',
    uri: Uri.parse('/admin/staff/staff_form'),
    routeBuilder: b4Builder,
  ),
  RouteEntity(
    key: '/admin/staff',
    uri: Uri.parse('/admin/staff'),
    routeBuilder: b5Builder,
  ),
  RouteEntity(key: '/login', uri: Uri.parse('/login'), routeBuilder: b6Builder),
  RouteEntity(
    key: '/shared/chat/ai_chat',
    uri: Uri.parse('/shared/chat/ai_chat'),
    routeBuilder: b7Builder,
  ),
  RouteEntity(
    key: '/shared/chat',
    uri: Uri.parse('/shared/chat'),
    routeBuilder: b8Builder,
  ),
  RouteEntity(
    key: '/shared/notes',
    uri: Uri.parse('/shared/notes'),
    routeBuilder: b9Builder,
  ),
  RouteEntity(
    key: '/splash',
    uri: Uri.parse('/splash'),
    routeBuilder: b10Builder,
  ),
  RouteEntity(
    key: '/staff/home/room_detail',
    uri: Uri.parse('/staff/home/room_detail'),
    routeBuilder: b11Builder,
  ),
  RouteEntity(
    key: '/staff/home/staff_dashboard',
    uri: Uri.parse('/staff/home/staff_dashboard'),
    routeBuilder: b12Builder,
  ),
  RouteEntity(
    key: '/staff/home/staff_rooms',
    uri: Uri.parse('/staff/home/staff_rooms'),
    routeBuilder: b13Builder,
  ),
  RouteEntity(
    key: '/staff/settings/change_password',
    uri: Uri.parse('/staff/settings/change_password'),
    routeBuilder: b14Builder,
  ),
];

const routePaths = (
  path: '/',
  admin: (
    path: '/admin',
    chat: (path: '/admin/chat', adminChat: '/admin/chat/admin_chat'),
    overview: '/admin/overview',
    rooms: (path: '/admin/rooms', roomForm: '/admin/rooms/room_form'),
    staff: (path: '/admin/staff', staffForm: '/admin/staff/staff_form'),
  ),
  login: '/login',
  shared: (
    path: '/shared',
    chat: (path: '/shared/chat', aiChat: '/shared/chat/ai_chat'),
    notes: '/shared/notes',
  ),
  splash: '/splash',
  staff: (
    path: '/staff',
    home: (
      path: '/staff/home',
      roomDetail: '/staff/home/room_detail',
      staffDashboard: '/staff/home/staff_dashboard',
      staffRooms: '/staff/home/staff_rooms',
    ),
    settings: (
      path: '/staff/settings',
      changePassword: '/staff/settings/change_password',
    ),
  ),
);
